### ISSUE TITLE
demo中关于retrofit的api中entity文件夹为空

### ISSUE THREAD

**Issue by argyili** [ssseasonnn/RxJava2Demo#7]
之前已有类似的issue 但未被解决

`

    @GET
    Observable<LoginResponse> login(@Body LoginRequest request);

    @GET
    Observable<RegisterResponse> register(@Body RegisterRequest request);

    @GET
    Observable<UserBaseInfoResponse> getUserBaseInfo(@Body UserBaseInfoRequest request);

    @GET
    Observable<UserExtraInfoResponse> getUserExtraInfo(@Body UserExtraInfoRequest request);
`

**Comment by ssseasonnn** [comment]
@GET
Observable<LoginResponse> login(@Body LoginRequest request);  去掉后面的@Body

**Comment by Acemonia** [comment]
好的谢谢

**Comment by argyili** [comment]
去掉@Body之后会报错
> No Retrofit annotation found.

只是相关的方法没有写出来吧

**Comment by ssseasonnn** [comment]
GET请求没有body, 把后面整个body注解和参数一起去掉就行

**Comment by argyili** [comment]
好的学习了
